//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctg_UnitType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ctg_UnitType()
        {
            this.Ctg_BaseUnits = new HashSet<Ctg_BaseUnits>();
            this.Ctg_MeasureUnits = new HashSet<Ctg_MeasureUnits>();
        }
    
        public int Pk_UnitType { get; set; }
        public string Uty_Type { get; set; }
        public System.DateTime Uty_CreatedAt { get; set; }
        public System.DateTime Uty_UpdatedAt { get; set; }
        public bool Uty_Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ctg_BaseUnits> Ctg_BaseUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ctg_MeasureUnits> Ctg_MeasureUnits { get; set; }
    }
}
