//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctg_Warehouses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ctg_Warehouses()
        {
            this.Tbl_Transfers = new HashSet<Tbl_Transfers>();
            this.Tbl_RemovedProducts = new HashSet<Tbl_RemovedProducts>();
            this.Tbl_WarehouseProducts = new HashSet<Tbl_WarehouseProducts>();
        }
    
        public int Pk_WarehouseID { get; set; }
        public string Whs_CustomID { get; set; }
        public string Whs_Name { get; set; }
        public string Whs_Description { get; set; }
        public System.DateTime Whs_CreatedAt { get; set; }
        public System.DateTime Whs_UpdatedAt { get; set; }
        public bool Whs_Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transfers> Tbl_Transfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RemovedProducts> Tbl_RemovedProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_WarehouseProducts> Tbl_WarehouseProducts { get; set; }
    }
}
