//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctg_Privilegies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ctg_Privilegies()
        {
            this.Ctg_Users = new HashSet<Ctg_Users>();
        }
    
        public int Pk_PrivilegieID { get; set; }
        public string Pvg_Name { get; set; }
        public System.DateTime Pvg_CreatedAt { get; set; }
        public System.DateTime Pvg_UpdatedAt { get; set; }
        public bool Pvg_Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ctg_Users> Ctg_Users { get; set; }
    }
}
