//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctg_Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ctg_Employees()
        {
            this.Ctg_Users = new HashSet<Ctg_Users>();
        }
    
        public int Pk_EmployeeID { get; set; }
        public string Emp_CustomID { get; set; }
        public string Emp_Position { get; set; }
        public string Emp_FirstName { get; set; }
        public string Emp_LastName { get; set; }
        public string Emp_PhoneNumber { get; set; }
        public string Emp_Address { get; set; }
        public string Emp_IdentificationCard { get; set; }
        public string Emp_EmailAddress { get; set; }
        public System.DateTime Emp_CreatedAt { get; set; }
        public System.DateTime Emp_UpdatedAt { get; set; }
        public bool Emp_Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ctg_Users> Ctg_Users { get; set; }
    }
}
