//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctg_ProductDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ctg_ProductDetails()
        {
            this.Tbl_RemovedProducts = new HashSet<Tbl_RemovedProducts>();
            this.Tbl_OrderDetails = new HashSet<Tbl_OrderDetails>();
            this.Tbl_SaleDetails = new HashSet<Tbl_SaleDetails>();
            this.Tbl_WarehouseProducts = new HashSet<Tbl_WarehouseProducts>();
            this.Tbl_TransferDetails = new HashSet<Tbl_TransferDetails>();
        }
    
        public int Pk_ProductDetailID { get; set; }
        public int Fk_ProductID { get; set; }
        public string Pdl_customID { get; set; }
        public int Fk_CategoryID { get; set; }
        public Nullable<int> Fk_BrandID { get; set; }
        public int Fk_UnitConversion { get; set; }
        public string Pdl_DefaultCode { get; set; }
        public string Pdl_Dimensions { get; set; }
        public string Pdl_MaterialType { get; set; }
        public Nullable<System.DateTime> Pdl_ExpiryDate { get; set; }
        public System.DateTime Pdl_CreatedAt { get; set; }
        public System.DateTime Pdl_UpdatedAt { get; set; }
        public bool Pdl_Deleted { get; set; }
    
        public virtual Ctg_Brands Ctg_Brands { get; set; }
        public virtual Ctg_Categories Ctg_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RemovedProducts> Tbl_RemovedProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderDetails> Tbl_OrderDetails { get; set; }
        public virtual Ctg_Products Ctg_Products { get; set; }
        public virtual Ctg_UnitConversion Ctg_UnitConversion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SaleDetails> Tbl_SaleDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_WarehouseProducts> Tbl_WarehouseProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TransferDetails> Tbl_TransferDetails { get; set; }
    }
}
