//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctg_DiscountPromotions
    {
        public int Pk_DiscountPromotionID { get; set; }
        public string Dtps_Name { get; set; }
        public string Dtps_Description { get; set; }
        public int Dtps_Discount { get; set; }
        public System.DateTime Dtps_CreateAt { get; set; }
        public System.DateTime Dtps_UpdatedAt { get; set; }
        public bool Dtps_Status { get; set; }
        public bool Dtps_Deleted { get; set; }
    }
}
