//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctg_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ctg_Users()
        {
            this.Tbl_Orders = new HashSet<Tbl_Orders>();
            this.Tbl_Transfers = new HashSet<Tbl_Transfers>();
            this.Tbl_Sales = new HashSet<Tbl_Sales>();
        }
    
        public int Pk_UserID { get; set; }
        public int Fk_EmployeeID { get; set; }
        public int Fk_PrivilegieID { get; set; }
        public string UserCustomID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserImage { get; set; }
        public System.DateTime UserCreatedAt { get; set; }
        public System.DateTime UserUpdatedAt { get; set; }
        public bool UserDeleted { get; set; }
    
        public virtual Ctg_Employees Ctg_Employees { get; set; }
        public virtual Ctg_Privilegies Ctg_Privilegies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Orders> Tbl_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transfers> Tbl_Transfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sales> Tbl_Sales { get; set; }
    }
}
