//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctg_UnitConversion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ctg_UnitConversion()
        {
            this.Ctg_ProductDetails = new HashSet<Ctg_ProductDetails>();
        }
    
        public int Pk_UnitConversion { get; set; }
        public int Fk_SourceUnit { get; set; }
        public string Utc_DestinationUnit { get; set; }
        public double Utc_Equivalence { get; set; }
        public System.DateTime Utc_CreatedAt { get; set; }
        public System.DateTime Utc_UpdatedAt { get; set; }
        public bool Utc_Deleted { get; set; }
    
        public virtual Ctg_MeasureUnits Ctg_MeasureUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ctg_ProductDetails> Ctg_ProductDetails { get; set; }
    }
}
