//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_WarehouseProducts
    {
        public int Fk_WarehouseID { get; set; }
        public int Fk_ProductDetailID { get; set; }
        public Nullable<int> WhPr_Stock { get; set; }
        public double WhPr_PurchasePrice { get; set; }
        public double WhPr_SalePrice { get; set; }
    
        public virtual Ctg_ProductDetails Ctg_ProductDetails { get; set; }
        public virtual Ctg_Warehouses Ctg_Warehouses { get; set; }
    }
}
