//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Taxes
    {
        public int Pk_TaxID { get; set; }
        public string TaxName { get; set; }
        public string TaxDescription { get; set; }
        public double TaxRate { get; set; }
        public System.DateTime TaxCreatedAt { get; set; }
        public System.DateTime TaxUpdatedAt { get; set; }
        public bool TaxDeleted { get; set; }
    }
}
