//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SaleDetails
    {
        public int Fk_SaleID { get; set; }
        public int Fk_ProductDetailID { get; set; }
        public int Fk_WarehouseId { get; set; }
        public double Sdt_Price { get; set; }
        public int Sdt_Quantity { get; set; }
        public Nullable<double> Sdt_Tax { get; set; }
        public double Sdt_Subtotal { get; set; }
        public Nullable<int> Sdt_Discount { get; set; }
        public double Sdt_Total { get; set; }
    
        public virtual Ctg_ProductDetails Ctg_ProductDetails { get; set; }
        public virtual Ctg_Warehouses Ctg_Warehouses { get; set; }
        public virtual Tbl_Sales Tbl_Sales { get; set; }
    }
}
