//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Transfers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Transfers()
        {
            this.Tbl_TransferDetails = new HashSet<Tbl_TransferDetails>();
        }
    
        public int Pk_TransferID { get; set; }
        public Nullable<int> Fk_UserID { get; set; }
        public int Fk_DestinationWarehouse { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<int> TransferTotal { get; set; }
        public Nullable<bool> TransferStatus { get; set; }
    
        public virtual Ctg_Users Ctg_Users { get; set; }
        public virtual Ctg_Warehouses Ctg_Warehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TransferDetails> Tbl_TransferDetails { get; set; }
    }
}
