//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HardwareStore
    {
        public string Hws_Name { get; set; }
        public string Hws_RUCNumber { get; set; }
        public string Hws_Address { get; set; }
        public string Hws_Description { get; set; }
        public string Hws_EmailAddress { get; set; }
        public string Hws_PhoneNumber { get; set; }
        public string Hws_FixedLineNumber { get; set; }
        public string Hws_OwnerName { get; set; }
        public System.DateTime Hws_CreatedAt { get; set; }
        public System.DateTime Hws_UpdatedAt { get; set; }
    }
}
